# Generated by Django 6.1.1 on 2026-09-11 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(choices=[('2E', 'Segundo E'), ('2F', 'Segundo F'), ('2D', 'Segundo D')], max_length=2, verbose_name='Curso Beneficiado')),
                ('parrilla', models.CharField(choices=[('P1', 'Parrilla 1'), ('P2', 'Parrilla 2'), ('P3', 'Parrilla 3'), ('P4', 'Parrilla 4')], default='P1', max_length=2, verbose_name='Parrilla Asignada')),
                ('turno', models.CharField(choices=[('T1', 'Turno 1 - Mañana'), ('T2', 'Turno 2 - Tarde'), ('T3', 'Turno 3 - Cierre')], max_length=2, verbose_name='Turno de Venta')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad de Anticuchos')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Total a Pagar ($)')),
                ('completado', models.BooleanField(default=False, verbose_name='¿Entregado en Parrilla?')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
