# Generated by Django 6.1.1 on 2026-09-11 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='curso',
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente',
            field=models.CharField(default='Cliente', max_length=100, verbose_name='Nombre del Cliente'),
        ),
        migrations.AddField(
            model_name='venta',
            name='curso_cajero',
            field=models.CharField(choices=[('2E', 'Segundo E'), ('2F', 'Segundo F'), ('2D', 'Segundo D')], default='Cliente', max_length=2, verbose_name='Curso del Cajero'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='medio_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia')], default='EFECTIVO', max_length=15, verbose_name='Medio de Pago'),
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_recibido',
            field=models.PositiveIntegerField(default=0, verbose_name='Paga con ($)'),
        ),
        migrations.AddField(
            model_name='venta',
            name='vuelto',
            field=models.PositiveIntegerField(default=0, verbose_name='Vuelto ($)'),
        ),
    ]
