# Generated by Django 6.1 on 2026-08-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('total', models.IntegerField()),
                ('metodo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Máquina', 'Máquina'), ('Transferencia', 'Transferencia')], default='Efectivo', max_length=20)),
                ('palabra_ticket', models.CharField(max_length=100)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
