# Generated by Django 6.1 on 2026-08-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('Completada', 'Completada'), ('Anulada', 'Anulada')], default='Completada', max_length=20),
        ),
    ]
