# Generated by Django 6.1 on 2026-08-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_venta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='despacho',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Entregado', 'Entregado')], default='Pendiente', max_length=20),
        ),
    ]
