# Generated by Django 6.1 on 2026-08-28 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_venta_despacho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='disponible',
        ),
        migrations.AddField(
            model_name='producto',
            name='estacion',
            field=models.CharField(choices=[('Bar', 'Bar (Bebidas/Terremotos)'), ('Cocina', 'Cocina (Empanadas/Papas)'), ('Parrilla', 'Parrilla (Choripanes/Anticuchos)')], default='Cocina', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='detalle_items',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.categoria'),
        ),
    ]
