# Generated by Django 6.1 on 2026-08-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_producto_descripcion_producto_disponible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='despacho',
        ),
        migrations.AddField(
            model_name='venta',
            name='bar_entregado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venta',
            name='cocina_entregado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venta',
            name='parrilla_entregado',
            field=models.BooleanField(default=False),
        ),
    ]
